os: windows

language: cpp

script:
  - choco install chocolatey
  - choco install make
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - make
  - make test
  - bin/test
compiler:
  - g++
  - gcc
